### ISSUE TITLE
MNIST_data/mnist_train/里的test跟train都是txt文件呀，请问图片在哪呢？

### ISSUE THREAD

**Issue by tomoya92** [mrlittlepig/ImageProcessing#3]
假如我用程序生成了 A-Z 26个字母的图片各100张，拿来训练，那我应该怎么替换呢？

谢谢

**Comment by mrlittlepig** [comment]
图片在ImageProcessing/MNIST_data/MNIST_data.zip里面，需要解压到当前目录，解压后的目录里面包括图片文件，按照文件夹名称来对0-9共10个数进行的分类，训练这些图片可以用项目根目录下的classification.py也可以用生成的tfrecord通过根目录下的classifier.py来训练。
如果你想训练自己的图片，推荐先将图片转化成tfrecord然后用classifier.py调用net目录下的网络结构来训练，具体顺序为
```
1.生成数据，调用脚本ImageProcessing/datasets/tfrecord.py，需要修改图片尺寸，和你的数据对应；
2.修改网络结构，可以按照ImageProcessing/net/lenet.py来修改里面的结构，网路结构需要和你的数据尺寸对应，如果你图片大小为28x28灰度图则不需要修改网络结构；
3.运行classifier.py开始训练，大致需要修改的地方是输入参数data_params和net_parans,需要数据尺寸和种类数为你自己数据的尺寸和种类，网络结构为你用的网络结构。
```

**Comment by tomoya92** [comment]
谢谢回复，MNIST_data.zip 解压了确实有图片数据了

我用程序生成了A-N 14个字母，label不是数字，用的是字母，类似下面这样
```
1.png A
2.png B
3.png C
```

在做tfrecords的时候，有个错误`invalid literal for int() with base 10: 'I'` 看了下，原来 `tf.train.Feature` 的数据类型只有三个，`BytesList` `FloatList` `Int64List` label这里选的是 `Int64List`，所以出错了

这里应该是要转换一下数据的，请问比较好的处理方式是什么呢？

**Comment by mrlittlepig** [comment]
label只能是以0开头的数，A-Z就用0-25做label，然后你的tfrecord 里面 num_classes应该是26代表有26类

**Comment by tomoya92** [comment]
嗯，我把它转成1-14没报错了
```py
    label_value = 0
    if label_record[name] == 'A':
      label_value = 1
    elif label_record[name] == 'B':
      label_value = 2
    # ....
    example = tf.train.Example(
      features=tf.train.Features(feature={
        "label": tf.train.Feature(int64_list=tf.train.Int64List(value=[int(label_value)])),
        'bytesImg': tf.train.Feature(bytes_list=tf.train.BytesList(value=[bytesImg]))
      }))
```

然后用classifier.py来训练生成的tfrecords文件的时候，又出了个错

```
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'data/lenet', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x11b3bc668>, '_task_type': 'worker', '_task_id': 0, '_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Create CheckpointSaverHook.
2017-11-28 16:52:48.796479: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 92160 values, but the requested shape requires a multiple of 3136
	 [[Node: Reshape_1 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](max_pooling2d_2/MaxPool, Reshape_1/shape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tomoya/Desktop/ml/ImageProcessing/classifier.py", line 123, in <module>
    main()
  File "/Users/tomoya/Desktop/ml/ImageProcessing/classifier.py", line 112, in main
    hooks=[logging_hook])
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 783, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 521, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 892, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 967, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1024, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 827, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 92160 values, but the requested shape requires a multiple of 3136
	 [[Node: Reshape_1 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](max_pooling2d_2/MaxPool, Reshape_1/shape)]]

Caused by op 'Reshape_1', defined at:
  File "/Users/tomoya/Desktop/ml/ImageProcessing/classifier.py", line 123, in <module>
    main()
  File "/Users/tomoya/Desktop/ml/ImageProcessing/classifier.py", line 112, in main
    hooks=[logging_hook])
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 711, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 694, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/Users/tomoya/Desktop/ml/ImageProcessing/net/lenet.py", line 72, in model_fn
    logits = mnist_model(features, mode, params['data_format'])
  File "/Users/tomoya/Desktop/ml/ImageProcessing/net/lenet.py", line 55, in mnist_model
    pool2_flat = tf.reshape(pool2, [-1, 7 * 7 * 64])
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3938, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 92160 values, but the requested shape requires a multiple of 3136
	 [[Node: Reshape_1 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](max_pooling2d_2/MaxPool, Reshape_1/shape)]]
```

我生成的图片参数分别是 

```
data_params = {
  'model_root': 'data',
  'data_dir': 'mydata',
  'data_format': 'channels_last',
  'num_classes': 14,
  'image_size': [50, 50, 3], # 3是我加的，我生成的图片是彩色的
  'num_images': {
    'train': 14000,
    'validation': 1400
  }
}
```
对应程序里也作了修改

```py
# classifier.py 方法 def input_fn(is_training, filename, batch_size=1, num_epochs=1):
    # ....
    image.set_shape([init_params['data_params']['image_size'][0]
                     * init_params['data_params']['image_size'][1]
                     * init_params['data_params']['image_size'][2]])
    #....
```

lenet.py 里的 image_size 我也改成了 `image_size = (50, 50, 3)`
```py
# lenet.py 方法 def mnist_model(inputs, mode, data_format):
    #...
    inputs = tf.reshape(inputs, [-1, image_size[0], image_size[1], image_size[2]])
    #...
```
其它参数没修改过了

麻烦再帮我看看是什么原因吧，谢谢了 : )

**Comment by tomoya92** [comment]
我找到原因了，https://stackoverflow.com/questions/43010339/python-tensorflow-input-to-reshape-is-a-tensor-with-92416-values-but-the-re

把lenet.py里的 `  pool2_flat = tf.reshape(pool2, [-1, 7 * 7 * 64])` 换成 `  pool2_flat = tf.reshape(pool2, [-1, 12 * 12 * 64])` 就好了

不过我挺好奇的，这个7和12都分别是怎么算出来的？

**Comment by mrlittlepig** [comment]
7和12是网络结构最后计算出来的，有关卷积神经网络的计算可以看斯坦福的课程笔记http://cs231n.github.io/convolutional-networks/

**Comment by tomoya92** [comment]
好的，谢谢

另外问一下，训练结果非常低应该怎么优化呢?

我的训练集是A-N 14万张图片，测试集是1.4万张图片，测试下来，结果寒心 `{'accuracy': 0.067000002, 'loss': 7.5661214e+11, 'global_step': 140000}` 

图片大概都是长这个样子的

![default](https://user-images.githubusercontent.com/6915570/33316106-bd56f8e0-d46d-11e7-97dc-5d0451c160a0.png)

**Comment by mrlittlepig** [comment]
这种图片特征比较简单，如果颜色特征不重要可以把图片做二值化处理，转成灰度图然后resize到比较低的分辨率用简单的网络训练，可以尝试用lenet 28x28的输入尺寸来训练；如果想用分辨率高的图片来训练，就需要对你的输入图片的尺寸专门设计较深的网络这样对数据的适应性强，更容易收敛。

**Comment by tomoya92** [comment]
对的，就是因为颜色的问题，我今天把图片都换成黑白的了，训练量是昨天的1/10，结果是 `{'accuracy': 0.86428571, 'loss': 68347496.0, 'global_step': 14000}` 

最后再次谢谢大大的解答，明白了不少东西 : )
